#! /usr/bin/python

import sys
import subprocess
import os
import imp
import site


def main(args):
  scriptPath = os.path.dirname(os.path.realpath(__file__))
  
  jarPath = os.path.join(scriptPath, "llfisrc/LLFI-GUI/llfi_gui.jar")

  majorVer = sys.version_info[0]
  minorVer = sys.version_info[1]
  pyVersion = str(majorVer) + "." + str(minorVer)
  pyPath = os.path.join(scriptPath, "pyyaml/lib/python"+pyVersion+"/site-packages/")
  os.environ['PYTHONPATH'] = pyPath
  
  os.chdir("llfisrc/LLFI-GUI/")
  p = subprocess.call(["java", "-jar", jarPath], env=os.environ)

if __name__=="__main__":
  main(sys.argv)
