#!/usr/bin/python

#traceDiff.py
#  Author: Sam Coulter
#  This python script is part of the greater LLFI system.
#  This script will examine two tracing output files generated by running a program after
#  the LLFI traceInst pass has been performed.
#   Exec: traceDiff.py goldenTrace faultyTrace
#  Input: GoldenTrace/faultyTrace - Trace output files after running a traced program
#  Output: Trace Summary into Standard output, redirect with PIPE to save to file


import sys
import os
import subprocess
import glob

class diffLine:
  def __init__(self, rawLine):
    self.raw = rawLine
    elements = str(rawLine).split()
    #ID: 14\tOPCode: sub\tValue: 1336d337
    assert (elements[0] in ["ID:"] and elements[2] == "OPCode:" and  \
      elements[4] == "Value:"), "DiffLine constructor called incorrectly"
    self.ID = int(elements[1])
    self.OPCode = str(elements[3])
    self.Value = str(elements[5])

  def _print(self):
    print "ID:",self.ID, "OPCode", self.OPCode, "Value:", self.Value

  def __str__(self):
    return self.raw

def traceDiff(argv, output = 0):
  #save stdout so we can redirect it without mangling other python scripts
  oldSTDOut = sys.stdout
  
  if output != 0:
    sys.stdout = open(output, "w")
  if (len(argv) != 3):
    print "ERROR: running option: traceDiff <golden output> <faulty output>"
    exit(1)

  goldFile = open(argv[1], 'r')
  goldTrace = goldFile.read()
  goldFile.close()

  faultyFile = open(argv[2], 'r')
  faultyTrace = faultyFile.read()
  faultyFile.close()

  goldTraceLines = goldTrace.split("\n")
  goldTraceLines = goldTrace.split("\n")
  faultyTraceLines =  faultyTrace.split("\n")

  #Examine Header of Trace File
  header = faultyTraceLines[0].split(' ')
  for i in range(0, len(header) - 1):
    keyword = header[i]
    if keyword == "#TraceStartInstNumber:":
    #Remove traces from golden trace that happened before fault injection point
      faultyTraceStartPoint = int(header[i+1])
      faultyTraceLines.pop(0)
      for i in range (0,faultyTraceStartPoint-1):
        goldTraceLines.pop(0)

  #goldTraceLines vs faultyTraceLines

  #record and report the fault injected line
  goldInjectedLine = diffLine(goldTraceLines[0])
  faultInjectedLine = diffLine(faultyTraceLines[0])
  diffID = goldInjectedLine.ID
  print "#Fault at instruction number: ", faultyTraceStartPoint
  print "#", goldInjectedLine.raw, "/", faultInjectedLine.Value

  #remove the fault injected lines
  goldTraceLines.pop(0)
  faultyTraceLines.pop(0)

  for line in goldTraceLines:
    if line == "":
      goldTraceLines.remove(line)

  for line in faultyTraceLines:
    if line == "":
      faultyTraceLines.remove(line)

  lenGT = len(goldTraceLines) - 1
  lenFT = len(faultyTraceLines) - 1
  
  i = 0

  postDiffID = -1

  while (faultyTraceLines[lenFT-i] == goldTraceLines[lenGT-i]):
    postDiffID = diffLine(goldTraceLines[lenGT-i]).ID
    faultyTraceLines.pop(lenFT-i)
    goldTraceLines.pop(lenGT-i)    
    i = i + 1
    if lenFT-i < 0 or lenGT-i < 0:
      break

  if lenFT-i > 0:
    faultyFlow = "Fault Flow: "
    for line in faultyTraceLines:
      faultyFlow += " " + str(diffLine(line).ID)
    if postDiffID >= 0:
      faultyFlow += " ->" + str(postDiffID)
    print faultyFlow

  if lenGT-i > 0:
    goldFlow = "Gold Flow: "
    for line in goldTraceLines:
        goldFlow += " " + str(diffLine(line).ID)
    if postDiffID >= 0:
        goldFlow = " ->" + str(postDiffID)
    print goldFlow

  #restore stdout
  sys.stdout = oldSTDOut

if (__name__ == "__main__"):
  traceDiff(sys.argv)
